### ISSUE TITLE
Internal Server Error when authenticating with OAuth via Nextcloud

### ISSUE THREAD

**Issue by Eisfunke** [codimd/server#118]
Hello everyone,

when trying to log-in to my CodiMD using OAuth2 after authenticating on my Nextcloud I get an Internal Server Error on `https://<mycodimd>/auth/oauth2/callback?state=&code=<code`.

The log shows:

```
Jun 17 18:16:51 sapphire run[3116]: InternalOAuthError: Failed to obtain access token
Jun 17 18:16:51 sapphire run[3116]:     at OAuth2CustomStrategy.OAuth2Strategy._createOAuthError (/var/codimd/node_modules/passport-oauth2/lib/strategy.js:408:17)
Jun 17 18:16:51 sapphire run[3116]:     at /var/codimd/node_modules/passport-oauth2/lib/strategy.js:175:45
Jun 17 18:16:51 sapphire run[3116]:     at /var/codimd/node_modules/oauth/lib/oauth2.js:191:18
Jun 17 18:16:51 sapphire run[3116]:     at ClientRequest.<anonymous> (/var/codimd/node_modules/oauth/lib/oauth2.js:162:5)
Jun 17 18:16:51 sapphire run[3116]:     at ClientRequest.emit (events.js:193:13)
Jun 17 18:16:51 sapphire run[3116]:     at TLSSocket.socketErrorListener (_http_client.js:397:9)
Jun 17 18:16:51 sapphire run[3116]:     at TLSSocket.emit (events.js:193:13)
Jun 17 18:16:51 sapphire run[3116]:     at emitErrorNT (internal/streams/destroy.js:91:8)
Jun 17 18:16:51 sapphire run[3116]:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
Jun 17 18:16:51 sapphire run[3116]:     at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

The OAuth2 part of my `config.json`:
```
"oauth2": {
            "clientID": "<client id>",
            "clientSecret": "<client secret>",
            "authorizationURL": "https://<my cloud>/apps/oauth2/authorize",
            "tokenURL": "https://<my cloud>/apps/oauth2/api/v1/token",
            "userProfileURL": "https://<my cloud>/ocs/v2.php/cloud/user?format=json",
            "userProfileUsernameAttr": "ocs.data.id",
            "userProfileDisplayNameAttr": "ocs.data.display-name",
            "userProfileEmailAttr": "ocs.data.email"
        },
```

This has some similarities to the problem I had when first setting up my CodiMD: <https://github.com/hackmdio/codimd/issues/1056>.

I can't really say when it worked the last time, but it did once, but now I can't log back in anymore. Any ideas?

**Comment by SISheogorath** [comment]
Can you check that your CodiMD instance can reach the Nextcloud server (like `curl https://<my cloud>` within the CodiMD container/on the CodiMD server)?

It seems like it has a problem with reaching it (otherwise it shouldn't throw a socket issue).

**Comment by Eisfunke** [comment]
Well then. I was sure it would work because both applications run on the same machine, so of course they should be able to reach each other – but it seems I screwed up my DNS config so my CodiMD couldn't resolve the URL. I fixed the DNS config, it works again now.
Sorry and thanks for the help!

**Comment by cs-qyzhang** [comment]
Hi, I have the same problem when configuring oauth2 with nextcloud, the hedgedoc server and nextcloud server are the same, I can do `curl https://<my-nextcloud-domain>` and `curl https://<my-hedgedoc-domain>` on the server.

The hedgedoc log:

```
InternalOAuthError: Failed to obtain access token
    at OAuth2CustomStrategy.OAuth2Strategy._createOAuthError (/root/hedgedoc/node_modules/passport-oauth2/lib/strategy.js:408:17)
    at /root/hedgedoc/node_modules/passport-oauth2/lib/strategy.js:175:45
    at /root/hedgedoc/node_modules/oauth/lib/oauth2.js:191:18
    at ClientRequest.<anonymous> (/root/hedgedoc/node_modules/oauth/lib/oauth2.js:162:5)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

The nginx configuration:

```
upstream @hedgedoc {
    server 127.0.0.1:13000;
    keepalive 300;
}

map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
}

# redirect all http traffic to https
server {
        listen 80;
        listen [::]:80;
        server_name mydomain;
        return 301 https://$server_name$request_uri;
}

server {
        server_name mydomain;

        listen [::]:443 ssl http2;
        listen 443 ssl http2;

        ssl_certificate /etc/ssl/nginx/mydomain.crt;
        ssl_certificate_key /etc/ssl/nginx/mydomain.key;

        location / {
                proxy_http_version 1.1;

                proxy_set_header Host $host; 
                proxy_set_header X-Real-IP $remote_addr; 
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;

                proxy_read_timeout 300;
                proxy_connect_timeout 300;
                proxy_pass http://@hedgedoc;
        }
}
```

Some of the hedgedoc config:

```
{
    "production": {
        "domain": "my-hedgedoc-domain",
        "host": "127.0.0.1",
        "port": 13000,
        "protocolUseSSL": true,
        "useSSL": false,
        "urlAddPort": false,
        "loglevel": "info",
        "hsts": {
            "enable": true,
            "maxAgeSeconds": 31536000,
            "includeSubdomains": true,
            "preload": true
        },
        "csp": {
            "enable": true,
            "directives": {
            },
            "upgradeInsecureRequests": "auto",
            "addDefaults": true,
            "addDisqus": true,
            "addGoogleAnalytics": true
        },
        "oauth2":
        {
          "clientID": "myID",
          "clientSecret": "mySecret",
          "authorizationURL": "https://<my-nextcloud-domain>/apps/oauth2/authorize",
          "tokenURL": "https://<my-nextcloud-domain>/apps/oauth2/api/v1/token",
          "userProfileURL": "https://<my-nextcloud-domain>/ocs/v2.php/cloud/user?format=json",
          "userProfileUsernameAttr": "ocs.data.id",
          "userProfileDisplayNameAttr": "ocs.data.display-name",
          "userProfileEmailAttr": "ocs.data.email"
        }
    }
}
```

**Comment by SISheogorath** [comment]
@cs-qyzhang please post this request not in years old issues. These days we have a shiny community forum at: https://community.hedgedoc.org

It provides a support category that is suited for such requests :)
