### ISSUE TITLE
Local image uploads does not work with the default configuration

### ISSUE THREAD

**Issue by Himura2la** [codimd/server#130]
## How to reproduce:

* Deploy version 1.4.0 in the container using the https://github.com/codimd/container/ repo.
* Set `CMD_IMAGE_UPLOAD_TYPE=filesystem`
* Upload an image from the clipboard
* Get the exception:

```
2019-07-04T08:20:11.465Z info:  172.23.0.1 - - [04/Jul/2019:08:20:11 +0000] "GET /me HTTP/1.1" 304 - "http://localhost:3000/mjC297BsTX-Gxbm8_Oh93A" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"

2019-07-04T08:20:12.349Z error:         *********/uploads/
2019-07-04T08:20:12.353Z error:         uncaughtException: Invalid URL: /uploads/
TypeError [ERR_INVALID_URL]: Invalid URL: /uploads/
    at onParseError (internal/url.js:219:17)
    at parse (internal/url.js:228:3)
    at new URL (internal/url.js:311:5)
    at new URL (internal/url.js:309:14)
    at Object.exports.uploadImage (/codimd/lib/web/imageRouter/filesystem.js:20:19)
    at /codimd/lib/web/imageRouter/index.js:31:22
    at IncomingForm.<anonymous> (/codimd/node_modules/formidable/lib/incoming_form.js:107:9)
    at emitNone (events.js:106:13)
    at IncomingForm.emit (events.js:208:7)
    at IncomingForm._maybeEnd (/codimd/node_modules/formidable/lib/incoming_form.js:557:8)
    at /codimd/node_modules/formidable/lib/incoming_form.js:238:12
    at WriteStream.<anonymous> (/codimd/node_modules/formidable/lib/file.js:79:5)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at WriteStream.emit (events.js:208:7)
    at finishMaybe (_stream_writable.js:613:14)
2019-07-04T08:20:12.353Z error:         An uncaught exception has occured.
2019-07-04T08:20:12.353Z error:         Invalid URL: /uploads/
2019-07-04T08:20:12.353Z error:         Process will exit now.
```

The line `2019-07-04T08:20:12.349Z error:         *********/uploads/` is me trying to debug the issue. I added the `logger.error('*********' + config.serverURL + /uploads/)` line before the https://github.com/codimd/server/blob/master/lib/web/imageRouter/filesystem.js#L19 line. As you see, the `config.serverURL` is empty for some reason. Looks line a bug.

**Comment by Himura2la** [comment]
Adding `CMD_DOMAIN` helps. But I guess it's not so hard to fix and make this feature work with the default configuration

**Comment by loliconer** [comment]
@Himura2la The final url will include the port if using this env, just like: `https://${CMD_DOMAIN}:3000/uploads/file.png`

**Comment by davidmehren** [comment]
Please note that [since 1.3.0](https://github.com/codimd/server/commit/a4941be3de3b849a6b1e4885b4801f3987125ba0) we warn on startup if the domain is not configured correctly. If no domain is configured, we are unable to generate a `serverUrl` and fail.
I'm not sure how we could handle this in a better way (beside not starting at all).

**Comment by muety** [comment]
This worked for me: https://github.com/codimd/server/issues/67#issuecomment-657397949
