### ISSUE TITLE
SequelizeDatabaseError: column "deleteToken" does not exist

### ISSUE THREAD

**Issue by almereyda** [codimd/server#315]
After upgrading a HackMD 1.1 instance to CodiMD 1.6 (and migrating config.json settings to environment variables), when trying to login with GitLab I am presented with an error that says

```
app_1       |
app_1       | 2020-03-30T04:08:09.980Z error:   auth callback failed: SequelizeDatabaseError: column "deleteToken" does not exist
app_1       | SequelizeDatabaseError: column "deleteToken" does not exist
app_1       |     at Query.formatError (/codimd/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)
app_1       |     at /codimd/node_modules/sequelize/lib/dialects/postgres/query.js:72:18
app_1       |     at tryCatcher (/codimd/node_modules/bluebird/js/release/util.js:16:23)
app_1       |     at Promise._settlePromiseFromHandler (/codimd/node_modules/bluebird/js/release/promise.js:547:31)
app_1       |     at Promise._settlePromise (/codimd/node_modules/bluebird/js/release/promise.js:604:18)
app_1       |     at Promise._settlePromise0 (/codimd/node_modules/bluebird/js/release/promise.js:649:10)
app_1       |     at Promise._settlePromises (/codimd/node_modules/bluebird/js/release/promise.js:725:18)
app_1       |     at _drainQueueStep (/codimd/node_modules/bluebird/js/release/async.js:93:12)
app_1       |     at _drainQueue (/codimd/node_modules/bluebird/js/release/async.js:86:9)
app_1       |     at Async._drainQueues (/codimd/node_modules/bluebird/js/release/async.js:102:5)
app_1       |     at Immediate.Async.drainQueues [as _onImmediate] (/codimd/node_modules/bluebird/js/release/async.js:15:14)
app_1       |     at processImmediate (internal/timers.js:456:21)
app_1       | 2020-03-30T04:08:09.989Z info:    172.18.0.1 - - [30/Mar/2020:04:08:09 +0000] "GET /auth/gitlab/callback?code=redacted HTTP/1.1" 500 148 "https://hack.allmende.io/" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0"
app_1       |
```

It also says

    app_1       | 2020-03-30T04:06:33.253Z error:   column owner.deleteToken does not exist

when trying to open a note, or its static representation.

May it be that some kind of migration from old database tables is missing?

**Comment by almereyda** [comment]
Duplicate of https://github.com/hackmdio/codimd/issues/895
