### ISSUE TITLE
keycloak callback error 502

### ISSUE THREAD

**Issue by seevik2580** [codimd/server#422]
i used manual installation with this `https://github.com/codimd/server/blob/master/docs/setup/manual-setup.md` and nginx reverse proxy, using:
- node v12.18.1
- npm v6.14.5

i tried to setup keycloak authentication method, and after successful login app crashes with error:
```
2020-06-23T15:41:26.416Z error: 	uncaughtException: The "url" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Url.parse (url.js:159:3)
    at Object.urlParse [as parse] (url.js:154:13)
    at exports.OAuth2._request (/root/server/node_modules/oauth/lib/oauth2.js:72:22)
    at exports.OAuth2.get (/root/server/node_modules/oauth/lib/oauth2.js:227:8)
    at OAuth2CustomStrategy.userProfile (/root/server/lib/web/auth/oauth2/index.js:66:16)
    at loadIt (/root/server/node_modules/passport-oauth2/lib/strategy.js:374:17)
    at OAuth2CustomStrategy.OAuth2Strategy._loadUserProfile (/root/server/node_modules/passport-oauth2/lib/strategy.js:389:25)
    at /root/server/node_modules/passport-oauth2/lib/strategy.js:177:16
    at /root/server/node_modules/oauth/lib/oauth2.js:209:7
    at passBackControl (/root/server/node_modules/oauth/lib/oauth2.js:134:9)
    at IncomingMessage.<anonymous> (/root/server/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-06-23T15:41:26.416Z error: 	An uncaught exception has occured.
2020-06-23T15:41:26.417Z error: 	The "url" argument must be of type string. Received undefined
2020-06-23T15:41:26.417Z error: 	Process will exit now.
```

**my userinfo**
```
{
  "sub": "9f64fcd9-a0c4-49e4-9dd0-2ef0e35aaa56",
  "email_verified": true,
  "name": "codi md",
  "id": "9f64fcd9-a0c4-49e4-9dd0-2ef0e35aaa56",
  "preferred_username": "codimd",
  "given_name": "codi",
  "family_name": "md"
}
```
**my token**
```
{
  "exp": 1592931273,
  "iat": 1592930973,
  "jti": "dad5f2d6-ee74-45ac-9362-552941cabe20",
  "iss": "https://keycloakurl",
  "sub": "9f64fcd9-a0c4-49e4-9dd0-2ef0e35aaa56",
  "typ": "Bearer",
  "azp": "codimd",
  "session_state": "8226795f-5782-4e13-bd7b-423e44df4008",
  "acr": "1",
  "allowed-origins": [
    "http://codimdurl"
  ],
  "realm_access": {
    "roles": [
      "uma_authorization"
    ]
  },
  "scope": "email id profile",
  "email_verified": true,
  "name": "codi md",
  "id": "9f64fcd9-a0c4-49e4-9dd0-2ef0e35aaa56",
  "preferred_username": "codimd",
  "given_name": "codi",
  "family_name": "md"
}
```
**my config.json**
```
	"oauth2": {
            "providerName": "Keycloak",
            "baseURL": "https://keycloakurl/",
            "userProfileUrl": "https://keycloakurl/auth/realms/global/protocol/openid-connect/userinfo",
            "userProfileUsernameAttr": "preferred_username",
            "userProfileDisplayNameAttr": "name",
	    "userProfileEmailAttr": "email",
            "tokenURL": "https://keycloakurl/auth/realms/global/protocol/openid-connect/token",
            "authorizationURL": "https://keycloakurl/auth/realms/global/protocol/openid-connect/auth",
            "clientID": "codimd",
	    "clientSecret": "top-secret"
        },
```
i tried to insert `console.log(url)` inside `./node_modules/oauth/lib/oauth2.js` at line 73

result:
```
https://keycloakurl/auth/realms/global/protocol/openid-connect/token
undefined
2020-06-23T18:05:18.476Z error: 	uncaughtException: The "url" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Url.parse (url.js:159:3)
    at Object.urlParse [as parse] (url.js:154:13)
    at exports.OAuth2._request (/root/server/node_modules/oauth/lib/oauth2.js:74:22)
    at exports.OAuth2.get (/root/server/node_modules/oauth/lib/oauth2.js:229:8)
    at OAuth2CustomStrategy.userProfile (/root/server/lib/web/auth/oauth2/index.js:66:16)
    at loadIt (/root/server/node_modules/passport-oauth2/lib/strategy.js:374:17)
    at OAuth2CustomStrategy.OAuth2Strategy._loadUserProfile (/root/server/node_modules/passport-oauth2/lib/strategy.js:389:25)
    at /root/server/node_modules/passport-oauth2/lib/strategy.js:177:16
    at /root/server/node_modules/oauth/lib/oauth2.js:211:7
    at passBackControl (/root/server/node_modules/oauth/lib/oauth2.js:136:9)
    at IncomingMessage.<anonymous> (/root/server/node_modules/oauth/lib/oauth2.js:159:7)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-06-23T18:05:18.476Z error: 	An uncaught exception has occured.
2020-06-23T18:05:18.476Z error: 	The "url" argument must be of type string. Received undefined
2020-06-23T18:05:18.476Z error: 	Process will exit now.
```

can you help me solve this pls? i dont know what to do :( thanks <3

**Comment by seevik2580** [comment]
i tried to insert `console.log(url)` inside `./node_modules/oauth/lib/oauth2.js` at line 73

result:
```
https://keycloakurl/auth/realms/global/protocol/openid-connect/token
undefined
2020-06-23T18:05:18.476Z error: 	uncaughtException: The "url" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Url.parse (url.js:159:3)
    at Object.urlParse [as parse] (url.js:154:13)
    at exports.OAuth2._request (/root/server/node_modules/oauth/lib/oauth2.js:74:22)
    at exports.OAuth2.get (/root/server/node_modules/oauth/lib/oauth2.js:229:8)
    at OAuth2CustomStrategy.userProfile (/root/server/lib/web/auth/oauth2/index.js:66:16)
    at loadIt (/root/server/node_modules/passport-oauth2/lib/strategy.js:374:17)
    at OAuth2CustomStrategy.OAuth2Strategy._loadUserProfile (/root/server/node_modules/passport-oauth2/lib/strategy.js:389:25)
    at /root/server/node_modules/passport-oauth2/lib/strategy.js:177:16
    at /root/server/node_modules/oauth/lib/oauth2.js:211:7
    at passBackControl (/root/server/node_modules/oauth/lib/oauth2.js:136:9)
    at IncomingMessage.<anonymous> (/root/server/node_modules/oauth/lib/oauth2.js:159:7)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2020-06-23T18:05:18.476Z error: 	An uncaught exception has occured.
2020-06-23T18:05:18.476Z error: 	The "url" argument must be of type string. Received undefined
2020-06-23T18:05:18.476Z error: 	Process will exit now.

```

**Comment by SISheogorath** [comment]
Sorry for the late reply, but what version of CodiMD are you running? 1.6.0 or the latest master?

**Comment by seevik2580** [comment]
latest master cloned from https://github.com/codimd/server.git

**Comment by SISheogorath** [comment]
Did you use yarn or npm to install the dependencies? If you used npm, please try using `yarn` instead. The error in that position of the oauth lib doesn't make a lot of sense for the error message that is provided.

**Comment by seevik2580** [comment]
i did this
```
curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -
yum install nodejs yarn mysql-server
- #alter database codimd character set utf8 collate utf8_bin;
npm install node-gyp
git clone https://github.com/codimd/server.git
cd server
bin/setup
- #made some changes inside config.json and .sequelizerc
yarn run build && npm start --production
```
i do not know node.js or yarn very much.

**Comment by seevik2580** [comment]
i tried more debugging at node_modules/oauth/lib/oauth2.js:73
```
console.log(c, method, url);
c = c + 1;
```
and it looks like there are two urls,  first for token, second is undefined in my case, dunno why.
```
1 POST https://id.trask.cz/auth/realms/global/protocol/openid-connect/token
2 GET undefined
```

**Comment by seevik2580** [comment]
well, i tried manualy set variable for second url inside node_modules/oauth/lib/oauth2.js:73
as userinfo url and it works. 

```
console.log(c, method, url, access_token);
  if( c == 2) {
    var url = "https://keycloakurl/auth/realms/global/protocol/openid-connect/userinfo"
  }
  if (c > 1) {
    c = 0;
  }
  c = c + 1;
```

i know its not proper method to make it work, but it works for me, keycloak login was successful and without crash

:)

**Comment by seevik2580** [comment]
ah, i found it ! 
permanent solution .. it was in capitalizing `userProfileUrl` to `userProfileURL`
removed oauth2.js modifications and it was successful.... now know if was my fault just misstype
i used this manual https://github.com/codimd/server/blob/master/docs/guides/auth/keycloak.md
and also https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-configuration#OAuth---General-OAuth2 to see variables
did not see clear that url word has to be CAPITALIZED :D

sorry guys and cheers <3
