### ISSUE TITLE
Clicking on non-existent reference crashes editor

### ISSUE THREAD

**Issue by matiasilva** [codimd/server#426]
Clicking on a reference that points to an internal non-existent heading crashes the editor and redirects to the home page.

Reproduced on demo.codimd.org:

![example4](https://user-images.githubusercontent.com/23108156/85996017-44c55600-b9f9-11ea-9d77-48ab0a8df6a4.gif)

**Comment by ErikMichelson** [comment]
The reason behind this is probably the usage of the `<base>` tag in the HTML that is delivered by CodiMD. Links are therefore based against the root domain instead of the actual document.

**Comment by dalcde** [comment]
The error logs on the server side are
```
2020-06-29T10:13:20.228Z error:         uncaughtException: Channel closed
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:636:16)
    at sendDmpWorker (/home/codimd/server/src/lib/models/revision.ts:62:13)
    at /home/codimd/server/src/lib/models/revision.ts:287:9
    at tryCatcher (/home/codimd/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/codimd/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/codimd/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/codimd/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/codimd/server/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/codimd/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/codimd/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/codimd/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/home/codimd/server/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
2020-06-29T10:13:20.230Z error:         An uncaught exception has occured.
2020-06-29T10:13:20.230Z error:         Channel closed
2020-06-29T10:13:20.231Z error:         Process will exit now.
```

**Comment by davidmehren** [comment]
The reason this happens is:
1. You click on a link to a non-existing anchor
2. The browser can't find it
3. The browser then follows the `base` tag and loads the home page to try and find the anchor there.

Unfortunately, fixing this would require us to check if the link leads to a non-existing anchor every time a link is clicked. This is somewhat complicated, so we decided to not implement a fix in 1.x. In the upcoming 2.0 release, this behavior does not occur.
