### ISSUE TITLE
Server crashes on upload to filesystem

### ISSUE THREAD

**Issue by MartiniMoe** [codimd/server#67]
I don't really know whats happening, maybe I misconfigured something, but I'm sure the server should not crash :D

```
2019-05-14T07:46:02.528Z error: 	uncaughtException: Invalid URL: /uploads/
TypeError [ERR_INVALID_URL]: Invalid URL: /uploads/
    at onParseError (internal/url.js:219:17)
    at parse (internal/url.js:228:3)
    at new URL (internal/url.js:311:5)
    at new URL (internal/url.js:309:14)
    at Object.exports.uploadImage (/codimd/lib/web/imageRouter/filesystem.js:19:19)
    at /codimd/lib/web/imageRouter/index.js:31:22
    at IncomingForm.<anonymous> (/codimd/node_modules/formidable/lib/incoming_form.js:107:9)
    at emitNone (events.js:106:13)
    at IncomingForm.emit (events.js:208:7)
    at IncomingForm._maybeEnd (/codimd/node_modules/formidable/lib/incoming_form.js:557:8)
    at /codimd/node_modules/formidable/lib/incoming_form.js:238:12
    at WriteStream.<anonymous> (/codimd/node_modules/formidable/lib/file.js:79:5)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at WriteStream.emit (events.js:208:7)
    at finishMaybe (_stream_writable.js:613:14)
2019-05-14T07:46:02.529Z error: 	An uncaught exception has occured.
2019-05-14T07:46:02.529Z error: 	Invalid URL: /uploads/
2019-05-14T07:46:02.530Z error: 	Process will exit now.
/usr/local/bin/docker-entrypoint.sh: 5: [: missing ]
```

This is my configuration:
```

      - CMD_DB_URL=postgres://hackmd:hackmdpass@database:5432/hackmd
      - CMD_IMAGE_UPLOAD_TYPE=filesystem
      - CMD_ALLOW_GRAVATAR=false
      - CMD_USECDN=false
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_ALLOW_ANONYMOUS_EDITS=false
      - CMD_ALLOW_FREEURL=true
      - CMD_EMAIL=true
      - CMD_ALLOW_EMAIL_REGISTER=true
      - CMD_SESSION_SECRET=<RANDOM STRING>
```

**Comment by SISheogorath** [comment]
Please add `CMD_DOMAIN` and if you run behind a reverse proxy `CMD_PROTOCOL_USESSL` AND `CMD_URL_ADDPORT`.

This should fix your problems :) for details check our docs: https://github.com/codimd/server/blob/master/docs/configuration-env-vars.md

**Comment by MartiniMoe** [comment]
Thank you very much, I fixed my issue with your help :)
Just wanted to point to the fact, that the server crashes. Should I close this now?

**Comment by SISheogorath** [comment]
I guess some documentation in the `./docs` directory would be great, when you want to try yourself on writen a few lines of documentation, feel free to go :)

In general I think we are good here :)

**Comment by ccoenen** [comment]
I'm closing this ticket, but if you wish to reopen it, just let me know!

**Comment by muety** [comment]
To make it work behind a reverse proxy, I had to set `CMD_DOMAIN` properly as well as `CMD_PROTOCOL_USESSL=true` (although CodiMD itself doesn't talk encrypted to the proxy) and `CMD_URL_ADDPORT=false`.

Otherweise, requests would be blocked by Firefox, because of "CSP".
